"""MA-0: run the deterministic attack + TemporalGuard-ablation matrix through the
REAL SmartThings cloud (virtual devices on the real cloud), for parity with the
virtual / cloud-callback / live-HA targets.

It REUSES the exact deterministic group functions of run_experiments (g1
feasibility, g2 baseline/RQ3, g3 ablation/RQ4) so the SmartThings cells are
generated by identical logic to the other targets -- only the adapter changes.
Results go to a NEW file (results/smartthings.csv); metrics.csv is FROZEN and its
md5 is asserted unchanged. Scripted/rule-based agents only (deterministic anchor;
bounds API calls). Token from $SMARTTHINGS_TOKEN / .env, read at runtime.

  SMARTTHINGS_TOKEN=*** .venv/bin/python -m delaysteer.run_smartthings
  SMARTTHINGS_TOKEN=*** .venv/bin/python -m delaysteer.run_smartthings --groups g1,g3
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from . import run_experiments as E

METRICS = Path("results/metrics.csv")


def _md5(p: Path) -> str:
    return hashlib.md5(p.read_bytes()).hexdigest() if p.exists() else "(absent)"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--groups", default="g1,g2,g3",
                    help="comma list of g1 (feasibility), g2 (baseline/RQ3), g3 (ablation/RQ4)")
    ap.add_argument("--append", action="store_true",
                    help="keep existing results/smartthings.csv rows (run groups across processes)")
    args = ap.parse_args()
    groups = [g.strip() for g in args.groups.split(",") if g.strip()]
    home = "smartthings"
    out = Path("results")

    frozen_before = _md5(METRICS)
    E.ROWS.clear()
    E._FLUSH = False  # never let the reused harness write metrics.csv
    prior = []
    if args.append and (out / "smartthings.csv").exists():
        prior = list(csv.DictReader((out / "smartthings.csv").open()))
        print(f"(append) carrying {len(prior)} existing rows")

    print(f"\n##### TARGET: smartthings (REAL cloud, virtual devices) — groups {groups} #####",
          flush=True)
    if "g1" in groups:
        E.g1_feasibility([home])
    if "g2" in groups:
        E.g2_baseline([home])
    if "g3" in groups:
        E.g3_ablation([home])

    out.mkdir(exist_ok=True)
    all_rows = prior + E.ROWS
    fields = sorted({k for r in all_rows for k in r})
    with (out / "smartthings.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(all_rows)
    (out / "smartthings.json").write_text(json.dumps(all_rows, indent=2, default=str))

    frozen_after = _md5(METRICS)
    print(f"\nwrote results/smartthings.csv ({len(all_rows)} rows; +{len(E.ROWS)} this run)")
    print(f"metrics.csv md5 before={frozen_before} after={frozen_after} "
          f"-> {'UNCHANGED (frozen OK)' if frozen_before == frozen_after else '!!! CHANGED !!!'}")
    E.summarize()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
