#!/usr/bin/env python3
"""The trace tau(S, sigma), its security projection, and the endogenous diff.

A trace is the time-ordered log of (delivered messages, agent actions, world
states). Three things in the design are defined over it, and all three need the
same record, so they live together here.

**pi_sec -- the security projection.** Two traces that differ only by
inconsequential milliseconds are the same result. The design says pi_sec
"collapses timing differences below the platform's semantic resolution", which
is what makes reachability a statement about *outcomes* rather than about
floating-point clocks. It is also the honest fallback for Stage 0's exit
criterion: if byte-identical replay proves unreachable on a real inference
server -- ollama determinism at T=0 is not guaranteed across context length,
batch size, or a server restart -- then pi_sec equality is what the reachability
claims actually require, and it should be adopted deliberately and stated, not
substituted quietly.

**E(sigma) -- the endogenous set.** ``M_sigma \\ M_clean``: messages that exist
only because the schedule drove the agent into a branch that generated them.
This is the formal seat of "a delayed branch emits a message the clean run never
produces", and Recursive Temporal Steering holds when sigma delays one of them.

**The reproducibility certificate.** A trace plus the capability record and the
sampling regime is what lets someone else get the same answer.

Note on message signatures. `EndogenousDiff` compares on
``(type, semantic_key, cause_action)`` rather than on message id, because ids are
per-run sequence numbers: the same logical message gets a different ``sq`` when
an earlier branch changes how many messages preceded it. Comparing ids would
report every message after the first divergence as endogenous, which is exactly
the false positive that would make Recursive Temporal Steering look ubiquitous.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

# Event kinds
BOUNDARY = "boundary"     # the scheduler was offered a decision point
DELIVER = "deliver"       # a message reached the agent
GENERATE = "generate"     # a message came into existence (exogenous or endogenous)
ACT = "act"               # the agent took an action
GUARD = "guard"           # a guard verdict at a commit
STATE = "state"           # world state snapshot


@dataclass
class Event:
    t: float
    kind: str
    mid: str | None = None
    flow: str | None = None
    seq: int | None = None
    label: str | None = None          # action name, message semantic type, verdict
    endogenous: bool = False          # generated by an agent action, not by eps
    cause: str | None = None          # the action that caused a generated message
    payload: dict[str, Any] = field(default_factory=dict)

    def signature(self) -> tuple:
        """Run-independent identity, for diffing two executions.

        Deliberately excludes t, mid and seq: those encode *when* and *how many
        preceded*, both of which legitimately differ between a clean and an
        attacked run without meaning the message is new.
        """
        return (self.kind, self.label, self.cause)


@dataclass
class Trace:
    """tau(S, sigma)."""

    events: list[Event] = field(default_factory=list)
    meta: dict[str, Any] = field(default_factory=dict)

    # ----------------------------------------------------------- recording

    def record(self, t: float, kind: str, **kw) -> Event:
        e = Event(t=t, kind=kind, **kw)
        self.events.append(e)
        return e

    def __len__(self) -> int:
        return len(self.events)

    def of_kind(self, kind: str) -> list[Event]:
        return [e for e in self.events if e.kind == kind]

    # ---------------------------------------------------------- projection

    def security_projection(self, resolution: float = 0.0) -> tuple:
        """pi_sec(tau): outcome-equivalent form.

        Timestamps are bucketed to `resolution` (0 keeps them exact); message
        ids and sequence numbers are dropped, since they are per-run. What
        survives is the ordered sequence of *what happened*, which is what a
        security property is a predicate over.
        """
        out = []
        for e in self.events:
            if e.kind == BOUNDARY:            # a decision point is not an outcome
                continue
            t = round(e.t / resolution) * resolution if resolution > 0 else e.t
            out.append((round(t, 9), e.kind, e.label, e.endogenous))
        return tuple(out)

    def outcome_equal(self, other: "Trace", resolution: float = 0.0) -> bool:
        return self.security_projection(resolution) == other.security_projection(resolution)

    # ---------------------------------------------------------- endogenous

    def generated(self) -> list[Event]:
        return self.of_kind(GENERATE)

    def generated_signatures(self) -> list[tuple]:
        return [e.signature() for e in self.generated()]

    # ------------------------------------------------------------ storage

    def write(self, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("w") as fh:
            fh.write(json.dumps({"_meta": self.meta}) + "\n")
            for e in self.events:
                fh.write(json.dumps(asdict(e)) + "\n")
        return p

    @classmethod
    def load(cls, path: str | Path) -> "Trace":
        """Read a trace back. The reader the repo never had."""
        p = Path(path)
        events, meta = [], {}
        with p.open() as fh:
            for i, line in enumerate(fh):
                line = line.strip()
                if not line:
                    continue
                d = json.loads(line)
                if i == 0 and "_meta" in d:
                    meta = d["_meta"]
                    continue
                events.append(Event(**d))
        return cls(events=events, meta=meta)


def endogenous_diff(clean: Trace, attacked: Trace) -> dict[str, Any]:
    """Algorithm 6 -- E(sigma) and the Recursive Temporal Steering witness.

    Returns the messages that exist only under the attack, and whether the
    schedule delayed any of them. `delayed_mids` is what the caller passes from
    `Sched.delayed_ids()`; RTS holds when a delayed message is endogenous.
    """
    clean_sigs = list(clean.generated_signatures())
    out, remaining = [], list(clean_sigs)
    for e in attacked.generated():
        s = e.signature()
        if s in remaining:
            remaining.remove(s)          # multiset difference: a second copy of
            continue                     # the same message IS new
        out.append(e)
    return {
        "endogenous": out,
        "endogenous_signatures": [e.signature() for e in out],
        "n_endogenous": len(out),
        "clean_generated": len(clean_sigs),
        "attacked_generated": len(attacked.generated()),
    }


def rts_witness(clean: Trace, attacked: Trace, delayed_mids: Iterable[str]) -> dict[str, Any]:
    """Recursive Temporal Steering: does sigma delay a message that only exists
    because sigma drove the agent into the branch that generated it?

    This is the mechanism the design says separates DelaySteer from repeated
    independent TOCTOU, so it is reported as an explicit boolean with its
    witnesses rather than inferred from a rate.
    """
    d = endogenous_diff(clean, attacked)
    delayed = set(delayed_mids)
    witnesses = [e for e in d["endogenous"] if e.mid in delayed]
    return {
        **d,
        "rts": bool(witnesses),
        "rts_witnesses": [e.mid for e in witnesses],
        "delayed_mids": sorted(delayed),
    }
